### PR TITLE
Fix crash when data is missing in vis [gh-1205]

### LINKED ISSUE #1205: Catch data visualization errors with empty data.

### LINKED ISSUE #1207: Fix data visualization so candidate info is not overlapping on desktop
It appears to be a selector or react key issue.

### LINKED ISSUE #1208: Fix comparison data visualization to include pagination toggling on tablet viewpoints.
There currently is a pagination view on mobile viewport, but not on tablet. Include this pagination feature on tablet sizes as well

### LINKED ISSUE #1209: Update Info page of oae website to new copy provided by Susan

### LINKED ISSUE #1215: Implement an ergonomic way for public data visualization to be used for testing locally.

### PR DESCRIPTION
**Pull request by andrewbiang888**
- #1205 
- #1207 
- #1209
- #1208

### CODE REVIEW

File: app/src/Pages/Home/Home.js [hunk 1]
```diff
@@ -1056,7 +1057,7 @@ const Home = ({
                   campaign => campaign.campaignName === name
                 );
                 return (
-                  <React.Fragment key={name}>
+                  <React.Fragment key={`candidate-${name}-index`}>
```
Comment (pirtleshell) [inline app/src/Pages/Home/Home.js]: nit: i think you should avoid indices in a react key.

this is better than a pure index key because the name will distinguish it across data, but if the underlying list changes react will unnecessarily rerender this component just because the index is different

File: app/src/components/Visualizations/ContributorTypeBar.js [hunk 2]
```diff
@@ -7,6 +7,9 @@ import { HorizontalBarChart } from '@hackoregon/component-library';
 const { numeric, dollars } = civicFormat;
 
 function ContributionTypeBar({ data, count }) {
+  if (!data) {
+    return null;
+  }
```
Comment (pirtleshell) [inline app/src/components/Visualizations/ContributorTypeBar.js:12]: 🙌

**Review by pirtleshell — APPROVED** [review]

File: app/src/Pages/Home/Home.js (hunk 1 above)
Comment (andrewbiang888) [reply app/src/Pages/Home/Home.js]: I hear you and agree indices should not be used when naming keys. This however is not using the dynamic index, but rather is relying on the `${name}` to be the differentiator. The name + additional info helps me when using the react debugger. Bueno?

File: app/src/components/Visualizations/ContributorTypeBar.js (hunk 2 above)
Comment (andrewbiang888) [reply app/src/components/Visualizations/ContributorTypeBar.js:12]: image
